In [3]:
import pandas as pd 

In [5]:
df=pd.read_csv(r"C:\Users\Priya\Desktop\Projects-master\ReferenceProjects\Stock-Sentiment-Analysis-master\Data.csv",encoding='ISO-8859-1')

In [6]:
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

In [7]:
train=df[df['Date']<'20150101']
test=df[df['Date']>'20150101']

In [8]:
#Removing Punctuation
data=train.iloc[:,2:27]
data.replace("[^a-zA-Z]"," ",regex=True,inplace=True)

In [9]:
#Renaming Columns to numbers
list1=[str(i) for i in range(25)]
data.columns=list1

In [10]:
data.head()

0  \
0  A  hindrance to operations   extracts from the...   
1                                          Scorecard   
2                  Coventry caught on counter by Flo   
3                      Pilgrim knows how to progress   
4                               Hitches and Horlocks   

                                    1  \
0                           Scorecard   
1                 The best lake scene   
2  United s rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                               2  \
0                Hughes  instant hit buoys Blues   
1                  Leader  German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                               3  \
0       Jack gets his skates on at ice cold Alex   
1                                  Cheerio  boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                             4  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers  are you all whingers    

                                                   5  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees    
2                                England on the rack   
3  Auntie back in fashion  even if the dress look...   
4                                   Hollywood Beyond   

                                                 6  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees    
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                   7  \
0                  Gunners so wide of an easy target   
1                             Has Cubie killed fees    
2               Cullinan continues his Cape monopoly   
3  Hussain hurt by  shambles  but lays blame on e...   
4                   Whingers   a formidable minority   

                                                   8  \
0      Derby raise a glass to Strupar s debut double   
1  Hopkins  furious  at Foster s lack of Hannibal...   
2             McGrath puts India out of their misery   
3                      England s decade of disasters   
4                             Alan Parker   part two   

                                          9  ...  \
0  Southgate strikes  Leeds pay the penalty  ...   
1                    Has Cubie killed fees   ...   
2            Blair Witch bandwagon rolls on  ...   
3      Revenge is sweet for jubilant Cronje  ...   
4                 Thuggery  Toxins and Ties  ...   

                                                  15  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne  Australia    
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere   UDIs   

                                                  16  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa  Mexico    
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted   Chloe lunettes   

                                               17  \
0             Kohl s successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid  Spain    
3    

In [11]:
#Converting headlines to same lowercase letters
for i in list1:
    data[i]=data[i].str.lower()
data.head(2)

0                    1  \
0  a  hindrance to operations   extracts from the...            scorecard   
1                                          scorecard  the best lake scene   

                                 2                                         3  \
0  hughes  instant hit buoys blues  jack gets his skates on at ice cold alex   
1    leader  german sleaze inquiry                             cheerio  boyo   

                                        4  \
0  chaos as maracana builds up for united   
1                the main recommendations   

                                                   5  \
0  depleted leicester prevail as elliott spoils e...   
1                             has cubie killed fees    

                                  6                                  7  \
0  hungry spurs sense rich pickings  gunners so wide of an easy target   
1            has cubie killed fees              has cubie killed fees    

                                                   8  \
0      derby raise a glass to strupar s debut double   
1  hopkins  furious  at foster s lack of hannibal...   

                                          9  ...  \
0  southgate strikes  leeds pay the penalty  ...   
1                    has cubie killed fees   ...   

                                         15  \
0  flintoff injury piles on woe for england   
1                      on the critical list   

                                                  16  \
0  hunters threaten jospin with new battle of the...   
1                          the timing of their lives   

                                    17  \
0  kohl s successor drawn into scandal   
1                          dear doctor   

                                                  18  \
0               the difference between men and women   
1  irish court halts ira man s extradition to nor...   

                                                  19  \
0                sara denver  nurse turned solicitor   
1  burundi peace initiative fades after rebels re...   

                                               20  \
0  diana s landmine crusade put tories in a panic   
1            pe points the way forward to the ecb   

                                                  21                22  \
0  yeltsin s resignation caught opposition flat f...  russian roulette   
1  campaigners keep up pressure on nazi war crime...    jane ratcliffe   

                                                  23  \
0                                           sold out   
1  yet more things you wouldn t know without the ...   

                             24  
0            recovering a title  
1  millennium bug fails to bite  

[2 rows x 25 columns]

In [12]:
' '.join(str(x) for x in data.iloc[0,0:25])

'a  hindrance to operations   extracts from the leaked reports scorecard hughes  instant hit buoys blues jack gets his skates on at ice cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton s party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar s debut double southgate strikes  leeds pay the penalty hammers hand robson a youthful lesson saints party like it s      wear wolves have turned into lambs stump mike catches testy gough s taunt langer escapes to hit     flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl s successor drawn into scandal the difference between men and women sara denver  nurse turned solicitor diana s landmine crusade put tories in a panic yeltsin s resignation caught opposition flat footed russian roulette sold out recovering a title'

In [13]:
headlines=[]
for i in range(0,len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[i,0:27]))

In [14]:
headlines[0]

'a  hindrance to operations   extracts from the leaked reports scorecard hughes  instant hit buoys blues jack gets his skates on at ice cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton s party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar s debut double southgate strikes  leeds pay the penalty hammers hand robson a youthful lesson saints party like it s      wear wolves have turned into lambs stump mike catches testy gough s taunt langer escapes to hit     flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl s successor drawn into scandal the difference between men and women sara denver  nurse turned solicitor diana s landmine crusade put tories in a panic yeltsin s resignation caught opposition flat footed russian roulette sold out recovering a title'

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [16]:
countvector=CountVectorizer(ngram_range=(2,2))
traindataset=countvector.fit_transform(headlines)

In [17]:
traindataset[0]

<1x584289 sparse matrix of type '<class 'numpy.int64'>'
	with 138 stored elements in Compressed Sparse Row format>

In [18]:
#implementing randomForest Classifier
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [19]:
test.head()

Date  Label                                               Top1  \
3975  2016-01-04      0  Saudi Arabia breaks off ties with Iran - Amid ...   
3976  2016-01-05      1  Dutch government backs strong encryption, cond...   
3977  2016-01-06      0  China shuts down stock market after 15 min 7% ...   
3978  2016-01-07      0  Reports of sexual assaults on women across Eur...   
3979  2016-01-08      0  El Chapo' Being Taken to Same Prison He Escape...   

                                                   Top2  \
3975  Exclusive: UK Government urged to reveal its r...   
3976  ISIS Militants Strap Bomb on 4 Year-Old Boy an...   
3977  Armed suspect shot dead after trying to storm ...   
3978  Shelter forcibly converted children to Christi...   
3979                           El Chapo has been caught   

                                                   Top3  \
3975              China halts trading as stocks fall 7%   
3976  Canada proceeding with controversial $15-billi...   
3977  Oil price falls below $35 a barrel to fresh 11...   
3978  Iran Has Banned Its Citizens from Making Pilgr...   
3979  At least 231 children abused at Catholic boys ...   

                                                   Top4  \
3975   Earthquake measuring 6.8 magnitude strikes India   
3976  Brazil is heading for its worst recession sinc...   
3977  Germans outraged by mayors advice for women af...   
3978  Gaddafi warned Blair his ousting would 'open d...   
3979  North Korea has defended its latest nuclear te...   

                                                   Top5  \
3975  A virus linked to shrinking newborns brains is...   
3976  British ISIS militant's desperate plea for doc...   
3977  German public broadcaster ZDF has apologised f...   
3978  A Turkish firm has been selling fake life vest...   
3979  A group of United Nations' experts have warned...   

                                                   Top6  \
3975  New photos of SpaceX booster show sooty, but u...   
3976  Malaysia's schools will start holding anti-ISI...   
3977  Iran accuses Saudis of bombing their embassy i...   
3978  German minister says deportations possible in ...   
3979  Gunman opens fire on hotel popular with wester...   

                                                   Top7  \
3975  Indian consulate in Afghanistan under attack b...   
3976  Saudi Arabia omitted from UK death penalty str...   
3977  Protesters demand Canada cancel $15B Saudi con...   
3978  Mao statue in China 'pulled down by authoritie...   
3979  French Proposal to Strip Citizenship Over Terr...   

                                                   Top8  ...  \
3975                          Iran calls off Major Hajj  ...   
3976  ISIS executes first female journalist. One of ...  ...   
3977  'Snooper's charter' will cost British lives, M...  ...   
3978  A poacher-hunting dog in South Africa has been...  ...   
3979  Hungary will never support EU sanctions agains...  ...   

                                                  Top16  \
3975  Iranian leaders website posts controversial im...   
3976  'Fat cat Tuesday' as top bosses pay overtakes ...   
3977  Rio Olympic stadium has no water or electricit...   
3978  Charlie Hebdo anniversary: free-speech groups ...   
3979  Swiss missionary has been kidnapped from her h...   

                                                  Top17  \
3975  After Bahrain, Sudan expels Iranian ambassador...   
3976  "The United Nations special rapporteur for hum...   
3977  Saudi-led air strikes in Yemen hit centre for ...   
3978  Polish president signs bill putting state medi...   
3979  NASA's Fermi satellite completes map of the sk...   

                                                  Top18  \
3975  Saudi Arabia to cut off all air traffic with I...   
3976  Merkel rejects Bavarian bid for refugee limit:...   
3977  Truck bomb kills 65 at Libyan police training ...   
3978            Mein Kampf hits stores in tense Germany   
3979  US condemns Israe

In [20]:
#Converting test data
test_transform=[]

for i in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[i,0:26]))
test_dataset=countvector.transform(test_transform)

In [21]:
#prediction for the test data
prediction=randomclassifier.predict(test_dataset)

In [22]:
test.loc[3975,:]

Date                                            2016-01-04
Label                                                    0
Top1     Saudi Arabia breaks off ties with Iran - Amid ...
Top2     Exclusive: UK Government urged to reveal its r...
Top3                 China halts trading as stocks fall 7%
Top4      Earthquake measuring 6.8 magnitude strikes India
Top5     A virus linked to shrinking newborns brains is...
Top6     New photos of SpaceX booster show sooty, but u...
Top7     Indian consulate in Afghanistan under attack b...
Top8                             Iran calls off Major Hajj
Top9     Denmark responds to Swedish border checks with...
Top10    David Cameron criticised for turning 'blind ey...
Top11    Denmark introduces temporary controls along Ge...
Top12    Israel Retaliates to Hezbollah bombing at Leba...
Top13    China Aims to Build 40 Nuclear Power Plants in...
Top14    According to obtained documents, after rape an...
Top15    Western Australian rooftop solar systems produ.

In [23]:
prediction

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [24]:
# Classification report,Confusion Matrix ,accuracy
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [25]:
matrix=confusion_matrix(test['Label'],prediction)
print(matrix)
score=accuracy_score(test['Label'],prediction)
print(score)
report=classification_report(test['Label'],prediction)
print(report)

[[10 46]
 [ 7 63]]
0.5793650793650794
              precision    recall  f1-score   support

           0       0.59      0.18      0.27        56
           1       0.58      0.90      0.70        70

    accuracy                           0.58       126
   macro avg       0.58      0.54      0.49       126
weighted avg       0.58      0.58      0.51       126



In [26]:
## Convert using Tfidfvectorizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

In [27]:
tfidfvector=TfidfVectorizer(ngram_range=(2,2))
traindataset=tfidfvector.fit_transform(headlines)

In [28]:
#implementing randomForest Classifier again
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [61]:
test_dataset=tfidfvector.transform(test_transform)
prediction=randomclassifier.predict(test_dataset)

In [62]:
prediction

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [63]:
matrix=confusion_matrix(test['Label'],prediction)
print(matrix)
score=accuracy_score(test['Label'],prediction)
print(score)
report=classification_report(test['Label'],prediction)
print(report)

[[14 42]
 [13 57]]
0.5634920634920635
              precision    recall  f1-score   support

           0       0.52      0.25      0.34        56
           1       0.58      0.81      0.67        70

    accuracy                           0.56       126
   macro avg       0.55      0.53      0.51       126
weighted avg       0.55      0.56      0.52       126



In [64]:
from sklearn.naive_bayes import MultinomialNB

In [65]:
traindataset

<3975x584289 sparse matrix of type '<class 'numpy.float64'>'
	with 1075856 stored elements in Compressed Sparse Row format>

In [66]:
multi_naive=MultinomialNB()
multi_naive.fit(traindataset,train['Label'])

MultinomialNB()

In [67]:
multi_naive

MultinomialNB()

In [68]:
#Converting test data
test_transform=[]

for i in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[i,0:26]))
test_dataset=tfidfvector.transform(test_transform)
prediction=multi_naive.predict(test_dataset)

In [69]:
prediction

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [70]:
matrix=confusion_matrix(test['Label'],prediction)
print(matrix)
score=accuracy_score(test['Label'],prediction)
print(score)
report=classification_report(test['Label'],prediction)
print(report)

[[ 0 56]
 [ 0 70]]
0.5555555555555556
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        56
           1       0.56      1.00      0.71        70

    accuracy                           0.56       126
   macro avg       0.28      0.50      0.36       126
weighted avg       0.31      0.56      0.40       126



C:\Users\Priya\Miniconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
